export const vn = {
  "title": {
    "require-login": "Bạn cần đăng nhập để sử dụng chức năng này!",
    "menu": "Danh sách",
    "title": "Ads Check by SMIT",
    "version": "Version 1.0.0",
    "create-by": "Tạo bởi",
    "sponsored-by": "& được tài trợ bởi",
    "dc-group": "DC Group",
    "product-of": "Một sản phẩm của ",
    "customization": "Tùy chỉnh bảng",
    "insight-edit": "Sửa",
    "save": "Lưu",
    "bm": "BM",
    "account": "Tài khoản",
    "account-info": "Thông tin tài khoản",
    "export-txt": " Xuất TXT",
    "edit-column": " Chỉnh cột",
    "detail": "Chi tiết",
    "apply": "Thực hiện",
    "cancel": "Hủy",
    "custom-range": "Custom Range",
    "enter-new-name": "Nhập tên mới tại đây",
    "rename-ad-account": "Đổi tên tài khoản quảng cáo",
    "remove-your-account": "Xoá bạn khỏi tài khoản",
    "you-not-own-this-account": "Bạn sẽ không còn sở hữu TKQC này sau khi xoá",
    "confirm": "Xác nhận",
    "back": "Quay lại",
    "add-ad-account": "Thêm TKQC",
    "delete-ad-account": "Xóa TKQC",
    "fill-ad-id": "Điền tên hoặc ID tài khoản cần thêm",
    "place-holder-permission": "Nhập nhiều ID cách bằng dấu phẩy ','",
    "account-permission": "Quyền tài khoản",
    "remove": "Xóa",
    "add-success": "Thêm thành công {adId}",
    "delete-success": "Xóa thành công {adId}",
    "id-invalid": "ID thất bại: {arrId}",
    "delete-except-you": "Xóa tất cả trừ bạn",
    "delete-yourself": "Xóa chính bạn",
    "change-account-permissions": "Đổi quyền TKQC",
    "number-of-account": "SL tài khoản: {num}",
    "rename-advertister": "Đổi tên TKQC",
    "repermission-advertister": "Đổi quyền TKQC",
    "refresh-data": "Làm mới dữ liệu",
    "currency-coversion": "Quy đổi tiền tệ",
    "row": "Hàng",
    "normal-user": "Cá nhân thường",
    "business": "Doanh nghiệp",
    "logout": "Đăng xuất",
    "assign-bm-role": "Chỉ định vai trò kinh doanh",
    "invite-people": "Mời mọi người",
    "user-mgmt": "Quản lý người dùng"
  },
  "messages": {
    "success": "Thành công",
    "login-again": "Đổi mật khẩu thành công, vui lòng đăng nhập lại",
    "not-update-account": "Không thể cập nhật tài khoản này!",
    "register-success": "Đăng kí thành công!",
    "send-account-mail-success": "Mật khẩu mới đã được gửi về hòm thư của  bạn!",
    "not-empty-input" : "Vui lòng không để trống thông tin",
    "wrong-password" : "Nhập sai mật khẩu",
    "not-same-password" : "Mật khẩu mới không được trùng với mật khẩu cũ",
    "not-match-new-password" : "Mật khẩu mới không trùng khớp",
    "resend-code-success": "Code đã được gửi lại. Vui lòng kiểm tra email."
  },
  "join-date": "Ngày tham  gia ",
  "enter-current-password": "Nhập mật khẩu của bạn",
  "enter-new-password": "Nhập mật khẩu mới",
  "re-enter-new-password": "Nhập lại mật khẩu mới",
  "change-password": "Đổi mật khẩu",
  "send-mail-description": "Tài khoản và mật khẩu mới sẽ được gửi về mail của bạn",
  "input-your-email": "Vui lòng nhập email của bạn",
  "login": "Đăng nhập",
  "enter-username": "Nhập tên tài khoản",
  "enter-password": "Nhập mật khẩu",
  "forget-password": "Quên tài khoản - mật khẩu?",
  "regist-account": "Đăng kí tài khoản",
  "confirm-password":  "Xác nhận mật khẩu",
  "full-name": "Họ và tên",
  "phone-number":  "Số điện thoại",
  "address": "Địa chỉ",
  "enter-email": "Nhập email",
  "no-account":  "Bạn chưa có tài khoản?",
  "sign-up-here": "Đăng kí tại đây",
  "log-in":  "Đăng nhập",
  "activity": "Hoạt động",
  "disable": "Vô hiệu hóa",
  "need-to-pay": "Cần thanh toán",
  "due-date": "Ân hạn",
  "other": "Khác",
  "status": "TT",
  "name": "Tên tài khoản",
  "bmName": "BM",
  "balance": "Số dư",
  "threshold_amount": "Ngưỡng",
  "adtrust_dsl": "Limited",
  "total": "Tổng tiêu",
  "currency": "Tiền tệ",
  "number_of_card": "SL thẻ",
  "role": "Vai trò",
  "next_bill_date": "Ngày nhập hóa đơn",
  "created_time": "Ngày tạo TK",
  "account_type": "Loại TK",
  "account_id": "ID",
  "last_id_card": "Đuôi thẻ",
  "remain_threshold": "Ngưỡng còn lại",
  "pay_day": "Số ngày đến kỳ TT",
  "disable_reason": "Lý do vô hiệu",
  "timezone": "Múi giờ",
  "bm": "Tạo từ BM",
  "business_country_code": "Quốc gia TKQC",
  "type": "Loại BM",
  "limit": "Giới hạn",
  "adHide": "Admin ẩn",
  "verified": "Xác thực",
  "created": "Ngày tạo",
  "id": "ID BM",
  "adNumber": "SL Admin",
  "accNumber": "SL account",
  "quality_bm": "Chất lượng BM",
  "administrator": "Quản trị viên",
  "advertiser": "Nhà quảng cáo",
  "analyst": "Nhà phân tích",
  "admin-access": "Quyền truy cập của quản trị viên",
  "employee-access": "Quyền truy cập của nhân viên",
}