export const en = {
    "label": {
        "no": "No",
        "interest": "Interest",
        "audiance-size": "Audiance Size",
        "action": "Action",
        "add-keyword": "Enter Keyword"
    },
    "title": {
        "require-login": "You must login to use advanced features.",
        "regist-subtitle": "Create your account.",
        "verify-email-subtitle": "Please check your email to recipe  OTP code.",
        "menu": "Menu",
        "title": "Ads Check",
        "version": "Version 1.0.1",
        "create-by": "Create by",
        "sponsored-by": "& Sponsored by",
        "dc-group": "DC Group",
        "product-of": "A product of the ",
        "customization": "Table option",
        "insight-edit": "Insight edit",
        "save": "Save",
        "bm": "BM",
        "account": "Account",
        "account-info": "Account Information",
        "export-txt": " Export TXT",
        "edit-column": " Edit column",
        "detail": " Detail",
        "apply": "Apply",
        "cancel": "Cancel",
        "custom-range": "Custom Range",
        "enter-new-name": "Enter new name here...",
        "rename-ad-account": "Rename AD account",
        "remove-your-account": "Remove your account",
        "you-not-own-this-account": "You aren't own this account after removal",
        "confirm": "Confirm",
        "back": "Back",
        "add-ad-account": "Add Account",
        "delete-ad-account": "Delete Account",
        "fill-ad-id": "Fill name or ID you want to add",
        "place-holder-permission": "Enter more ID by commas ','",
        "account-permission": "Select Account permission",
        "remove": "Remove",
        "add-success": "Add successfully {adId}",
        "delete-success": "Delete successfully {adId}",
        "id-invalid": "The IDs fail: {arrId}",
        "delete-except-you": "Delete all but you",
        "delete-yourself": "Delete yourself",
        "change-account-permissions": "Change permission account",
        "number-of-account": "Number of account: {num}",
        "rename-advertister": "Rename AD account",
        "repermission-advertister": "Repermission AD account",
        "refresh-data": "Refresh data",
        "currency-coversion": "Currency conversion",
        "row": "Row",
        "normal-user": "Normal user",
        "business": "Business",
        "logout": "Logout",
        "upgrade-account": "Upgrade Account",
        "super-target": "Super Target",
        "assign-bm-role": "Assign Business Role",
        "invite-people": "Invite people",
        "user-mgmt": "User management"
    },
    "messages": {
        "success": "Success",
        "delete-success": "Delete Success!",
        "wrong-password": "Wrong password",
        "register-success": "Register successfull!",
        "not-update-account": "Cannot update ad account",
        "not-match-new-password": "New passwords does not match",
        "not-empty-input": "Please do not leave input info  blank",
        "login-again": "Change password is success, please login again",
        "change-account-name-success": "Account name changed successfully!",
        "send-account-mail-success": "A new password was sent to your email!",
        "resend-code-success": "Code has been sent back. Please check your email",
        "not-same-password": "The new password cannot be the same as the old password",
    },
    "join-date": "Joined",
    "enter-current-password": "Enter current password",
    "enter-new-password": "Enter new password",
    "re-enter-new-password": "Re-Enter new password",
    "change-password": "Change Password",
    "send-mail-description": "A new password will send to your email",
    "input-your-email": "Please input your email",
    "login": "Login",
    "resend-email": "Resend Email",
    "resend-code": "Resend Code",
    "enter-code": "Enter code",
    "enter-username": "Enter username",
    "enter-your-email": "Enter email",
    "enter-password": "Password",
    "forget-password": "Forgot password?",
    "regist-account": "Regist account",
    "verify-account": "Verify",
    "verify-email": "Verify email address",
    "confirm-password": "Confirm password",
    "full-name": "Full name",
    "phone-number": "Phone number",
    "address": "Address",
    "enter-email": "Email Address",
    "not-member": "Not a member?",
    "have-an-account": "Already have an account?",
    "sign-up": "Sign up",
    "log-in": "Login",
    "activity": "Active",
    "disable": "Disable",
    "need-to-pay": "Need to pay",
    "due-date": "Due date",
    "other": "Other",
    "status": "Status",
    "name": "Account name",
    "bmName": "BM Name",
    "balance": "Balance",
    "threshold_amount": "Threshold",
    "adtrust_dsl": "Limited",
    "total": "Total",
    "currency": "Currency",
    "number_of_card": "Card's number",
    "role": "Role",
    "next_bill_date": "Invoice entry date",
    "created_time": "Account creation date",
    "account_type": "Account type",
    "account_id": "ID",
    "last_id_card": "Card numbers",
    "remain_threshold": "Remain threshold",
    "pay_day": "Number of days to pay period",
    "disable_reason": "Disable reason",
    "timezone": "Timezone",
    "bm": "Create from BM",
    "business_country_code": "Business country code",
    "type": "BM Type",
    "limit": "Limit",
    "adHide": "Hidden admin",
    "verified": "Verified",
    "created": "Created",
    "id": "ID BM",
    "adNumber": "No.Admin",
    "accNumber": "No.Account",
    "quality_bm": "Quality",
    "administrator": "Administrator",
    "advertiser": "Advertiser",
    "analyst": "Analyst",
    "admin-access": "Admin access",
    "employee-access": "Employee access",
}